site_name: Tanu Lab
theme:
  name: material
  favicon: assets/favicon.ico
  features:
    - content.code.annotate

docs_dir: './src'
site_dir: './docs'

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['./lab']
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

